# Data base connectivity
spring:
 data:
  mongodb:
   uri: ${MONGO_URI}
   database: ${MONGO_DB_NAME}
   
# Server Url
server:
 agri-bid-serve:
  url: https://agribid-server-1.onrender.com/agri-bid	   
   
   