# Data base connectivity
spring:
 data:
  mongodb:
   uri: ${MONGO_URI}
   database: ${MONGO_DB_NAME}
   auto-index-creation: true
   
# Server Url
service:
 agri-bid-server:
  url: https://agribid-server-1.onrender.com/agri-bid/
 quick-convo-server:
    url: https://quickconvo-server.onrender.com/   	   
 
# Server Error handling   
server:
 error:
  include-message: always  
  include-binding-errors: always
  include-stacktrace: on_param
  
# Cloud Storage Cred
cloud:  
 api:
  name: ${CLOUD_NAME}
  key: ${CLOUD_API_KEY}
  secret: ${CLOUD_API_SECRET}  
  
   
   